preset: symfony

linting: true

enabled:
    - newline_after_open_tag
    #- ordered_class_elements
    - ordered_use
    - phpdoc_order
    - short_array_syntax

    # Strict
    - strict_param
    #- declare_strict_types

finder:
    path:
        - 'src/'
        - 'tests/'
    not-path:
        - 'spec/'
        - 'Fixtures'
        - 'doc'
