<?php

/**
 * This file is part of the RollerworksRecordFilterBundle.
 *
 * (c) Sebastiaan Stok <s.stok@rollerscapes.net>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Rollerworks\RecordFilterBundle\Formatter\Modifier;

use Rollerworks\RecordFilterBundle\Formatter\FormatterInterface;
use Rollerworks\RecordFilterBundle\FilterConfig;
use Rollerworks\RecordFilterBundle\FilterValuesBag;

/**
 * ModifierInterface.
 *
 * @author Sebastiaan Stok <s.stok@rollerscapes.net>
 */
interface ModifierInterface
{
    /**
     * Returns the name of the modifier.
     *
     * This would normally be the class-name in lowercase and underscored.
     *
     * @return string
     */
    public function getModifierName();

    /**
     * Modifies the filters.
     *
     * Return null to remove the filter from the final result.
     *
     * @param FormatterInterface   $formatter
     * @param FilterConfig         $filterConfig
     * @param FilterValuesBag      $valuesBag
     * @param integer              $groupIndex Group the filter is in
     * @return integer[]|null
     */
    public function modFilters(FormatterInterface $formatter, FilterConfig $filterConfig, FilterValuesBag $valuesBag, $groupIndex);

    /**
     * Returns messages that where generated by the modifier.
     *
     * Should return at least an empty array.
     *
     * The message should be translate string or an array as: [[message], [params]]
     * [params] is an associative array containg the paramaters as %key% => value
     *
     * By default the following placeholders are available.
     * * %label%: Current field's label
     * * %group%: Current group (starting with 1)
     *
     * @return array
     */
    public function getMessages();
}