<?php

/**
 * This file is part of the RollerworksRecordFilterBundle.
 *
 * (c) Sebastiaan Stok <s.stok@rollerscapes.net>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Rollerworks\RecordFilterBundle\Formatter\Modifier;

use Rollerworks\RecordFilterBundle\Formatter\FormatterInterface;
use Rollerworks\RecordFilterBundle\Formatter\FilterConfig;
use Rollerworks\RecordFilterBundle\FilterStruct;

/**
 * Post modifier interface.
 *
 * Must be in implemente in the Formatter Post modifier.
 *
 * @author Sebastiaan Stok <s.stok@rollerscapes.net>
 */
interface PostModifierInterface
{
    /**
     * Returns the name of the modifier.
     * This would normally be the class-name in lowercase and underscored.
     *
     * @return string
     */
    public function getModifierName();

    /**
     * Modify the filters by object reference.
     * Return null to remove the filter from the final result.
     *
     * @param \Rollerworks\RecordFilterBundle\Formatter\FormatterInterface  $formatter
     * @param \Rollerworks\RecordFilterBundle\Formatter\FilterConfig        $filterConfig
     * @param \Rollerworks\RecordFilterBundle\FilterStruct                  $filterStruct
     * @param integer                                                       $groupIndex Group the filter is in
     * @return integer[]
     */
    public function modFilters(FormatterInterface $formatter, FilterConfig $filterConfig, FilterStruct $filterStruct, $groupIndex);

    /**
     * Return messages that where generated by the modifier.
     * Should return at least an empty array.
     *
     * The message should be either an transchoise string or an array as: [message, [params]]
     * [params] is an associative array containg the paramaters as %key% => value
     *
     * By default the following placeholders are available.
     * * %field%: Current field's label
     * * %group%: Current group (starting with 1)
     *
     * @return array
     */
    public function getMessages();
}