Text Fields
~~~~~~~~~~~

* :doc:`text </reference/types/text>`
* :doc:`integer </reference/types/integer>`
* :doc:`money </reference/types/money>`
* :doc:`number </reference/types/number>`

Choice Fields
~~~~~~~~~~~~~

* :doc:`choice </reference/types/choice>`
* :doc:`country </reference/types/country>`
* :doc:`language </reference/types/language>`
* :doc:`locale </reference/types/locale>`
* :doc:`timezone </reference/types/timezone>`
* :doc:`currency </reference/types/currency>`

Date and Time Fields
~~~~~~~~~~~~~~~~~~~~

* :doc:`date </reference/types/date>`
* :doc:`datetime </reference/types/datetime>`
* :doc:`time </reference/types/time>`
* :doc:`birthday </reference/types/birthday>`

Base Fields
~~~~~~~~~~~

* :doc:`field </reference/types/field>`
